# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mistinguette',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/mistinguette',
                'lib_path': 'mistinguette'},
  'syms': { 'mistinguette.core': { 'mistinguette.core.ChatCompletionResponse._repr_markdown_': ( 'core.html#chatcompletionresponse._repr_markdown_',
                                                                                                 'mistinguette/core.py'),
                                   'mistinguette.core.Client': ('core.html#client', 'mistinguette/core.py'),
                                   'mistinguette.core.Client.__init__': ('core.html#client.__init__', 'mistinguette/core.py'),
                                   'mistinguette.core.UsageInfo.__add__': ('core.html#usageinfo.__add__', 'mistinguette/core.py'),
                                   'mistinguette.core.UsageInfo.__repr__': ('core.html#usageinfo.__repr__', 'mistinguette/core.py'),
                                   'mistinguette.core.UsageInfo.total': ('core.html#usageinfo.total', 'mistinguette/core.py'),
                                   'mistinguette.core.contents': ('core.html#contents', 'mistinguette/core.py'),
                                   'mistinguette.core.find_block': ('core.html#find_block', 'mistinguette/core.py'),
                                   'mistinguette.core.usage': ('core.html#usage', 'mistinguette/core.py')}}}
