# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mistinguette',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/mistinguette',
                'lib_path': 'mistinguette'},
  'syms': {'mistinguette.core': {'mistinguette.core.foo': ('core.html#foo', 'mistinguette/core.py')}}}
